// DenX v0.7 Coordinate In-betweening — deterministic math, no AI.
(() => {
  "use strict";
  if(!document.getElementById("workspace")||window.denxTweenV070)return;window.denxTweenV070=true;
  const clone=value=>JSON.parse(JSON.stringify(value));
  const mix=(a,b,t)=>Number(a)+(Number(b)-Number(a))*t;
  const mixAngle=(a,b,t)=>{a=Number(a)||0;b=Number(b)||0;const delta=((b-a+540)%360)-180;return a+delta*t;};
  function tweenPoseMap(a={},b={},t){const output={};new Set([...Object.keys(a||{}),...Object.keys(b||{})]).forEach(figureId=>{const left=a?.[figureId],right=b?.[figureId];if(!left&&!right)return;if(!left||!right){output[figureId]=clone((t<.5?left:right)||left||right);return;}const pose=clone(left),target=right;pose.visible=left.visible===target.visible?left.visible:(t<.5?left.visible:target.visible);pose.nodes={};new Set([...Object.keys(left.nodes||{}),...Object.keys(target.nodes||{})]).forEach(nodeId=>{const p=left.nodes?.[nodeId],q=target.nodes?.[nodeId];if(p&&q)pose.nodes[nodeId]={x:mix(p.x,q.x,t),y:mix(p.y,q.y,t)};else pose.nodes[nodeId]=clone((t<.5?p:q)||p||q);});if(Number.isFinite(Number(left.denxStyleScale))&&Number.isFinite(Number(target.denxStyleScale)))pose.denxStyleScale=mix(left.denxStyleScale,target.denxStyleScale,t);pose.denxSegmentLengths={};new Set([...Object.keys(left.denxSegmentLengths||{}),...Object.keys(target.denxSegmentLengths||{})]).forEach(id=>{const x=left.denxSegmentLengths?.[id],y=target.denxSegmentLengths?.[id];pose.denxSegmentLengths[id]=Number.isFinite(Number(x))&&Number.isFinite(Number(y))?mix(x,y,t):Number(x??y);});output[figureId]=pose;});return output;}
  function tweenCamera(a,b,t){if(!a&&!b)return null;if(!a||!b)return clone((t<.5?a:b)||a||b);const out={...clone(a)};["x","y","width","height"].forEach(k=>{if(Number.isFinite(Number(a[k]))&&Number.isFinite(Number(b[k])))out[k]=mix(a[k],b[k],t);});out.rotation=mixAngle(a.rotation,b.rotation,t);return out;}
  function loadImage(src){return new Promise((resolve,reject)=>{if(!src){resolve(null);return;}const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("Could not read a drawing frame."));image.src=src;});}
  async function tweenDrawing(a,b,t){const canvas=document.getElementById("drawingCanvas"),out=document.createElement("canvas");out.width=Number(canvas?.width)||2048;out.height=Number(canvas?.height)||1152;const ctx=out.getContext("2d");const [left,right]=await Promise.all([loadImage(a),loadImage(b)]);ctx.clearRect(0,0,out.width,out.height);if(left){ctx.globalAlpha=1-t;ctx.drawImage(left,0,0,out.width,out.height);}if(right){ctx.globalAlpha=t;ctx.drawImage(right,0,0,out.width,out.height);}ctx.globalAlpha=1;return out.toDataURL("image/png");}

  const section=document.getElementById("tool-animation");
  const button=document.createElement("button");button.id="inbetweenToolBtn";button.type="button";button.className="tool-row tool-action denx-inbetween-tool";button.title="Generate a calculated frame between this frame and the next";button.innerHTML='<span class="tool-icon">◇</span><span class="tool-label">In-between</span>';
  section?.querySelector(".tool-section-title")?.insertAdjacentElement("afterend",button);
  const dialog=document.createElement("dialog");dialog.id="denxTweenDialog";dialog.className="denx-project-dialog denx-tween-dialog";dialog.innerHTML=`<div class="denx-dialog-head"><div><strong>In-between Frame</strong><small>Current pose → next pose</small></div><button class="close" type="button">×</button></div><p>Choose how far the generated pose should move toward the next frame.</p><div class="denx-tween-presets"><button data-ratio=".25">25%<small>Near current</small></button><button class="active" data-ratio=".5">50%<small>Halfway</small></button><button data-ratio=".75">75%<small>Near next</small></button></div><label class="denx-tween-custom"><span>Custom percentage</span><input type="number" min="1" max="99" value="50"><b>%</b></label><div class="denx-tween-preview"><span>Frame <b class="from">1</b></span><i>→</i><strong>NEW <b class="percent">50%</b></strong><i>→</i><span>Frame <b class="to">2</b></span></div><div class="denx-tween-status" hidden></div><button class="denx-export-start generate" type="button">CREATE IN-BETWEEN FRAME</button>`;document.body.appendChild(dialog);
  const input=dialog.querySelector("input"),presets=[...dialog.querySelectorAll("[data-ratio]")],generate=dialog.querySelector(".generate"),status=dialog.querySelector(".denx-tween-status");let ratio=.5;
  function sync(value){ratio=Math.max(.01,Math.min(.99,Number(value)||.5));input.value=String(Math.round(ratio*100));dialog.querySelector(".percent").textContent=`${Math.round(ratio*100)}%`;presets.forEach(x=>x.classList.toggle("active",Math.abs(Number(x.dataset.ratio)-ratio)<.001));}
  function open(){const frame=Number(window.denxCurrentFrame?.()||1),count=Number(window.denxFrameCount?.()||1);if(frame>=count){window.denxShowToast?.("The last frame has no next pose to calculate from.");return;}dialog.querySelector(".from").textContent=String(frame);dialog.querySelector(".to").textContent=String(frame+1);status.hidden=true;sync(.5);dialog.showModal?.();}
  button.addEventListener("click",open);dialog.querySelector(".close").addEventListener("click",()=>dialog.close?.());presets.forEach(x=>x.addEventListener("click",()=>sync(x.dataset.ratio)));input.addEventListener("input",()=>sync(Number(input.value)/100));
  generate.addEventListener("click",async()=>{const from=Number(window.denxCurrentFrame?.()||1),to=from+1;if(to>Number(window.denxFrameCount?.()||1)){status.hidden=false;status.textContent="A next frame is required.";return;}generate.disabled=true;status.hidden=false;status.textContent="Calculating every matching node…";try{window.denxStopPlayback?.();const timeline=window.denxTimelineCaptureSession?.(),snapshot=window.denxBonesCaptureProjectState?.()||{framePoses:{}},a=snapshot.framePoses?.[from]||snapshot.framePoses?.[String(from)]||{},b=snapshot.framePoses?.[to]||snapshot.framePoses?.[String(to)]||{},bonePose=tweenPoseMap(a,b,ratio),camera=tweenCamera(window.denxCameraFrameStates?.[from],window.denxCameraFrameStates?.[to],ratio),drawing=await tweenDrawing(timeline?.frames?.[from-1]||window.denxTimelineFrameData?.(from),timeline?.frames?.[to-1]||window.denxTimelineFrameData?.(to),ratio);window.denxInsertFrameAfterCurrent?.(drawing,null,camera,bonePose,{tweenRatio:ratio});window.denxMarkWorkspaceDirty?.();window.denxRefreshAllFrameThumbnails?.();dialog.close?.();window.denxShowToast?.(`Created ${Math.round(ratio*100)}% in-between frame ✓`);}catch(error){console.error("DenX tween failed",error);status.textContent=error?.message||"Could not create the in-between frame.";}finally{generate.disabled=false;}});
  window.denxCreateInbetweenFrame=async percentage=>{sync(Number(percentage)/100);generate.click();};
})();
